# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(default='student', max_length=50, verbose_name='type of user'),
            preserve_default=False,
        ),
    ]
