# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255, verbose_name='student first name')),
                ('countryOfStudy', models.CharField(max_length=255, verbose_name='country of study')),
                ('surname', models.CharField(max_length=255, verbose_name='student first name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('course', models.CharField(max_length=255, null=True, verbose_name='course name')),
                ('university', models.CharField(max_length=255, null=True, verbose_name='university name')),
            ],
        ),
    ]
