# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('HQ_city', models.CharField(max_length=255, verbose_name='HQ_city')),
                ('description', models.CharField(max_length=5000, null=True, verbose_name='short company description')),
                ('industry', models.CharField(max_length=255, verbose_name='company primary industry')),
            ],
        ),
    ]
