# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoietyData',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('society_name', models.CharField(max_length=255, verbose_name='Society name')),
                ('society_university', models.CharField(max_length=255, verbose_name='societys university')),
                ('society_description', models.CharField(max_length=5000, null=True, verbose_name='short society description')),
                ('society_facebook', models.CharField(max_length=255, null=True, verbose_name='society FB')),
                ('society_website', models.CharField(max_length=255, null=True, verbose_name='societys website')),
            ],
        ),
        migrations.AddField(
            model_name='companydata',
            name='company_website',
            field=models.CharField(default='null', max_length=255, verbose_name='company name'),
            preserve_default=False,
        ),
    ]
