# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20170128_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job title')),
                ('job_type', models.CharField(max_length=255, verbose_name='job type')),
                ('job_description', models.CharField(max_length=5000, verbose_name='company name')),
                ('Job_city', models.CharField(max_length=255, verbose_name='City, country')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='salary')),
                ('application_email', models.CharField(max_length=255, verbose_name='email')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('active_for', models.DateTimeField(default=datetime.datetime(2017, 5, 9, 11, 24, 31, 102800))),
                ('company_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.CompanyData')),
            ],
        ),
    ]
