# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='active_for',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 18, 7, 44, 306257)),
        ),
    ]
