# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_auto_20170129_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='active_for',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 19, 40, 30, 500462)),
        ),
    ]
